/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author Yahya
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfKalimat = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        tfHasil = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Program Cek Kalimat");
        setLocation(new java.awt.Point(500, 250));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfKalimat.setBackground(new java.awt.Color(255, 204, 0));
        tfKalimat.setFont(new java.awt.Font("Microsoft YaHei", 1, 28)); // NOI18N
        getContentPane().add(tfKalimat, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 1000, 90));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/cek.jpg"))); // NOI18N
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 610, 70, 50));

        tfHasil.setEditable(false);
        tfHasil.setBackground(new java.awt.Color(255, 204, 0));
        tfHasil.setFont(new java.awt.Font("Microsoft YaHei", 1, 28)); // NOI18N
        tfHasil.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(tfHasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 1010, 80));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/reset.jpg"))); // NOI18N
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 610, 80, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Anotasi 2018-12-05 223821.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField tfHasil;
    private javax.swing.JTextField tfKalimat;
    // End of variables declaration//GEN-END:variables

    public JButton getjButton1() {
        return jButton1;
    }

    public void setjButton1(JButton jButton1) {
        this.jButton1 = jButton1;
    }
    public void setTfHasil(String tfHasil) {
        this.tfHasil.setText(tfHasil);
    }

    public String getTfKalimat() {
        return tfKalimat.getText();
    }

    public void setTfKalimat(String tfKalimat) {
        this.tfKalimat.setText(tfKalimat);
    }
    public void addActionListener(ActionListener x) {
        jButton1.addActionListener(x);
        jButton2.addActionListener(x);
    }

    public String getTfHasil() {
        return tfHasil.getText();
    }

    
    public void refresh() {
        this.setTfKalimat("");
    }

    public JButton getjButton2() {
        return jButton2;
    }

    public void setjButton2(JButton jButton2) {
        this.jButton2 = jButton2;
    }
    
    

}
